spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
      config:
        enabled: true
        format: yaml
  config:
    import: 'consul:'
  application:
    name: notification-service

email:
  allowedEmails:
    - gmail.com
    - yahoo.com
    - outlook.com
    - hotmail.com
    - icloud.com
    - mail.com
    - aol.com
    - protonmail.com
    - recruiter-app.com
    - zoho.com
    - gmx.com
    - gmx.de
    - web.de
    - seznam.cz
    - wp.pl
    - o2.pl
    - onet.pl
    - interia.pl
    - gazeta.pl
    - poczta.fm
    - tlen.pl
    - ukr.net
    - bigmir.net